service:
  name: aws-nodejs-ecma-script

plugins:
  - serverless-webpack
  - serverless-offline-kinesis
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  listPolls:
    handler: polls/index.listPolls
    events:
      - http:
          method: get
          path: api/v1/polls
  createPoll:
    handler: polls/index.createPoll
    events:
      - http:
          method: post
          path: api/v1/polls
  getPoll:
    handler: polls/index.getPoll
    events:
      - http:
          method: get
          path: api/v1/polls/{id}
  updatePoll:
    handler: polls/index.updatePoll
    events:
      - http:
          method: put
          path: api/v1/polls/{id}
  removePoll:
    handler: polls/index.removePoll
    events:
      - http:
          method: delete
          path: api/v1/polls/{id}
  aggregate:
    namle: "aggregate"
    handler: polls/index.aggregate
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:eu-west-1:XXXXXX:stream/polls
          batchSize: 10
          # startingPosition: TRIM_HORIZON
          startingPosition: LATEST

custom:
  serverless-offline:
    port: 4000
  serverless-offline-kinesis:
    apiVersion: '2013-12-02'
    endpoint: http://localhost:4567
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
