service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  listPolls:
    handler: polls/index.listPolls
    events:
      - http:
          method: get
          path: polls
  createPoll:
    handler: polls/index.createPoll
    events:
      - http:
          method: post
          path: polls
  getPoll:
    handler: polls/index.getPoll
    events:
      - http:
          method: get
          path: polls/{id}
  updatePoll:
    handler: polls/index.updatePoll
    events:
      - http:
          method: put
          path: polls/{id}
  removePoll:
    handler: polls/index.removePoll
    events:
      - http:
          method: delete
          path: polls/{id}
  aggregate:
    namle: "aggregate"
    handler: polls/index.aggregate
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:eu-west-1:XXXXXX:stream/polls
          batchSize: 10
          startingPosition: TRIM_HORIZON

custom:
  serverless-offline:
    port: 4000
