swagger: "2.0"
info:
  title: "SixPoll"
  version: "1.0.0"
  description: ""
basePath: "/api"
tags:
- name: "polls"
  description: "Everything about your Polls"
schemes:
- "http"
consumes:
- "application/json; charset=utf-8"
produces:
- "application/json; charset=utf-8"
paths:
  /v1/polls:
    post:
      tags:
      - "polls"
      summary: "Add a new poll"
      description: ""
      operationId: "addPoll"
      parameters:
      - in: "body"
        name: "body"
        description: "Poll object"
        required: true
        schema:
          $ref: "#/definitions/Poll"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Poll"
        400:
          description: "Bad Request"
    get:
      tags:
      - "polls"
      summary: "List polls"
      description: ""
      operationId: "listPolls"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Polls"
  /v1/polls/{pollId}:
    get:
      tags:
      - "polls"
      summary: "Get poll"
      description: ""
      operationId: "getPoll"
      parameters:
      - name: "pollId"
        in: "path"
        description: "ID of poll to return"
        required: true
        type: "integer"
        format: "int64"
        x-example: 1
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Poll"
        404:
          description: "Not Found"
    put:
      tags:
      - "polls"
      summary: "List polls"
      description: ""
      operationId: "editPoll"
      parameters:
      - name: "pollId"
        in: "path"
        description: "ID of poll to return"
        required: true
        type: "integer"
        format: "int64"
        x-example: 1
      - in: "body"
        name: "body"
        description: "Poll object"
        required: true
        schema:
          $ref: "#/definitions/Poll"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Poll"
        404:
          description: "Not Found"
    delete:
      tags:
      - "polls"
      summary: "Remove polls"
      description: ""
      operationId: "removePoll"
      parameters:
      - name: "pollId"
        in: "path"
        description: "ID of poll to return"
        required: true
        type: "integer"
        format: "int64"
        x-example: 1
      responses:
        204:
          description: "No Content"
        404:
          description: "Not Found"
definitions:
  Poll:
    type: "object"
    properties:
      question:
        type: "string"
  Polls:
    type: "array"
    items:
      $ref: "#/definitions/Poll"
